# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- id: snap
  goos:
    - linux
  goarch:
    - 386
    - amd64
    - arm64
  ldflags: "-s -w -X main.version={{ .Version }}"
  hooks:
    post:
      upx
        dist/snap_linux_386/download-geofabrik
        dist/snap_linux_amd64/download-geofabrik
        dist/snap_linux_arm64/download-geofabrik
- id: no-snap
  goos:
    # - android # Not working and I'm not sure ther is anyone using download-geofabrik on android :D
    - darwin
    - dragonfly
    - freebsd
    - illumos
    - linux
    - netbsd
    - openbsd
    #- plan9
    - solaris
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - mips
    - mips64
    - mips64le
    - mipsle
    - ppc64
    - ppc64le
    - s390x
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: linux
      goarch: 386
    - goos: linux
      goarch: amd64
    - goos: linux
      goarch: arm64
  ldflags: "-s -w -X main.version={{ .Version }}"
  hooks:
    post:
      upx
        dist/no-snap_linux_arm_5/download-geofabrik
        dist/no-snap_linux_arm_6/download-geofabrik
        dist/no-snap_linux_arm_7/download-geofabrik
        dist/no-snap_windows_amd64/download-geofabrik.exe
        dist/no-snap_windows_386/download-geofabrik.exe
        dist/no-snap_darwin_amd64/download-geofabrik

archives:
-
  format_overrides:
  - goos: windows
    format: zip
  #replacements:
  #  darwin: MacOS
  #  linux: Linux
  #  windows: Windows
  #  386: i386
  #  amd64: x86_64
  files:
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  - bbbike.yml
  - geofabrik.yml
  - openstreetmap.fr.yml

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^refactor'
    - '^chore(deps):'
    - '^Deploy'
snapcrafts:
  - builds:
    - snap
    #replacements:
    #  amd64: 64-bit
    #  386: 32-bit
    #  darwin: macOS
    summary: A simple tool for downloading osm files.
    description: A simple tool for downloading OpenStreetMap files from Geofabrik, BBBike and openstreetmap-fr.
    license: MPL-2.0
    publish: true
    apps:
      download-geofabrik:
        plugs: ["home", "network"]
release:
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    #binaries:
    #  - download-geofabrik
    image_templates:
      - "juliennoblet/{{.ProjectName}}:latest"
      - "juliennoblet/{{.ProjectName}}:{{ .Tag }}"
      - "juliennoblet/{{.ProjectName}}:v{{ .Major }}"
      - "juliennoblet/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
    skip_push: auto
    dockerfile: Dockerfile
    extra_files:
      - geofabrik.yml
      - openstreetmap.fr.yml
      - bbbike.yml

