name: "Go Coverage"
permissions:
  # contents permission to update benchmark contents in 'benchmarks' branch
  contents: write
on:
  pull_request:
  push:
    branches:
      # It's important that the action also runs on merge to main
      - main
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # default fetch-depth is insufficent to find previous coverage notes
        fetch-depth: 10

    - uses: gwatts/go-coverage-action@v2
      id: coverage
      continue-on-error: true
      with:
        # Optional coverage threshold
        # use fail-coverage to determine what should happen below this threshold
        coverage-threshold: 70

        # collect coverage for all packages beyond the one under test
        cover-pkg: ./...

        # Ignore code-generated files when calculating coverage totals
        ignore-pattern: |
          \.pb\.go$
          \_string\.go$
        
        # A url that the html report will be accessible at, once your
        # workflow uploads it.  Used in the pull request comment.
        report-url: https://julien-noblet.github.io/download-geofabrik/${{ github.ref_name}}.html

    - name: Generate coverage tree map
      run: |
        mkdir -p ${{ github.ref_name}}
        go run github.com/nikolaydubina/go-cover-treemap@latest -coverprofile ${{ steps.coverage.outputs.gocov-agg-pathname }} -only-folders=true > ${{ github.ref_name}}.svg
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git fetch --all
        git checkout gh-pages
        mkdir -p ${{ github.ref_name}}
        cp -r ${{ steps.coverage.outputs.report-pathname }} ${{ github.ref_name}}.html
        git add ${{ github.ref_name}}.html ${{ github.ref_name}}.svg
        git commit -m "Upload coverage report"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        