---
name: Create changelog
on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: gen_changelog
        uses: hojland/github-changelog-action@v1.0.1