name: yml-generate
on:
  # pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
permissions:
  # contents permission to update benchmark contents in 'benchmarks' branch
  contents: write
jobs:
  yml-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
          cache: true
      - run: go run cmd/download-geofabrik/main.go generate
      - run: go run cmd/download-geofabrik/main.go --service="openstreetmap.fr" generate
      - run: go run cmd/download-geofabrik/main.go --service="bbbike" generate
      - run: go run cmd/download-geofabrik/main.go --service="geo2day" generate
      - run: go run cmd/download-geofabrik/main.go --service="movisda" generate
      - run: go run cmd/download-geofabrik/main.go --service="planet.osm.ch" generate
      - run: go run cmd/download-geofabrik/main.go --service="osm.kewl.lu" generate
      - run: go run cmd/download-geofabrik/main.go --service="osm.fit.vutbr.cz" generate
      - run: go run cmd/download-geofabrik/main.go --service="osmit-estratti" generate
      - run: go run cmd/download-geofabrik/main.go --service="osm.kcwu.csie.org" generate
      - run: cat .README.md1 > README.md
      - run: go run cmd/download-geofabrik/main.go --help >> README.md
      - run: cat .README.md2 >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>Geofabrik Extracts</strong> (default service)</summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>OpenStreetMap France Extracts (openstreetmap.fr)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "openstreetmap.fr" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>BBBike Extracts (bbbike.org)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "bbbike" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>Geo2day Extracts</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "geo2day" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>Movisda Extracts</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "movisda" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>Planet OSM Switzerland Extracts (planet.osm.ch)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "planet.osm.ch" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>OSM Luxembourg Extracts (osm.kewl.lu)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "osm.kewl.lu" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>FIT VUT Brno Extracts (osm.fit.vutbr.cz)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "osm.fit.vutbr.cz" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>OpenStreetMap Italia Extracts (osmit-estratti)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "osmit-estratti" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - run: echo "" >> README.md
      - run: echo "<details>" >> README.md
      - run: echo "<summary><strong>OSM Taiwan Extracts (osm.kcwu.csie.org)</strong></summary>" >> README.md
      - run: echo "" >> README.md
      - run: go run cmd/download-geofabrik/main.go --service "osm.kcwu.csie.org" list --markdown >> README.md
      - run: echo "" >> README.md
      - run: echo "</details>" >> README.md
      - uses: actions-js/push@master
        with:
          message: generate yaml files
          branch: new_yamls
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rebase: true
          force: true
