name: gotest
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.3' # The Go version to download (if necessary) and use.
          check-latest: true
          cache: true
      - run: go test -v ./