name: gotest
on:
  pull_request:
  push:
    branches:
      - main
      - master
env:
  CGO_ENABLED: 0
jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run tests
        run: nix develop --command go test -v ./...
