name: gotest

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Verify go mod tidy
        run: nix develop --command bash -c "go mod tidy && git diff --exit-code go.mod go.sum"
      - name: Run unit & race tests
        run: nix develop --command bash -c "CGO_ENABLED=1 go test -v -race -shuffle=on ./..."
