name: gobenchdata publish
concurrency:
  group: gh-pages-publish
  cancel-in-progress: false
permissions:
  # contents permission to update benchmark contents in 'benchmarks' branch
  contents: write
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Setup environment from Nix
      run: |
        nix develop --command bash -c 'echo "$PATH" | tr ":" "\n"' | while read -r p; do
          if [ -d "$p" ]; then
            echo "$p" >> "$GITHUB_PATH"
          fi
        done
    - name: gobenchdata publish
      uses: bobheadxi/gobenchdata@v1
      with:
        PRUNE_COUNT: 30
        GO_TEST_FLAGS: -cpu 1,2
        PUBLISH: true
        PUBLISH_BRANCH: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
